language: python
python:
  - "3.4"
  - "3.5"
before_install:
 - "sudo apt-get update -qq"
 - "sudo apt-get install --fix-missing mercurial python3-dev python3-numpy libav-tools libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev libsdl1.2-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev"
 - "pip install hg+http://bitbucket.org/pygame/pygame"
 - "pip install pytest-cov"
 - "pip install pytest-pep8"
 - "pip install python-coveralls"
  
before_script:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - mvn install:install-file -Dfile=/usr/local/share/OpenCV/java/opencv-300.jar -DgroupId=opencv -DartifactId=opencv -Dversion=3.0.0 -Dpackaging=jar
  - cd ../..
# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script:
  # We don't have Matlab on the Travis machines, so we're setting a dummy path
  # and ignoring the tests tagged for Matlab.
  - export MATLAB_LIBRARY_ROOT=/tmp
  - sbt "testOnly * -- -l MatlabTest"
  - py.test thin_client/test/